module.exports.ban = require('./ban')
module.exports.clear = require('./clear')
module.exports.kick = require('./kick')
module.exports.unban = require('./unban')
module.exports.slowmode = require('./slowmode')