module.exports.choose = require('./choose')
module.exports.help = require('./help')
module.exports.ping = require('./ping')
module.exports.profile = require('./profile')
module.exports.river = require('./river')
module.exports.register = require('./register')
module.exports.unregister = require('./unregister')
module.exports.corona = require('./corona')