module.exports.blacklist = require('./blacklist')
module.exports.eval = require('./eval')
module.exports.restart = require('./restart')
module.exports.exec = require('./exec')
module.exports.askreturn = require('./askreturn')